### ISSUE TITLE
There is no license set

### ISSUE THREAD

**Issue by baturinsky** [xem/mini2Dphysics#1]
I wanted to use it for js13kgames. 

Yes, I know it's nearly deadline, but I already has a main entry and liked this lib so much that I wanted to hack something simple with it too.

But then I have noticed that it's not licensed under any permissive license, and it's mentioned in code that it's "for educational purposes only". Therefore, it's pretty useless.

**Comment by xem** [comment]
Feel free to use it, I made it public domain ! :)

**Comment by Ryuno-Ki** [comment]
In #2 you referred to a book you used to derive the code.
https://github.com/Apress/building-a-2d-physics-game-engine/blob/master/LICENSE.txt claims to be under the „Freeware License” (not listed in SPDX), which looks different from „Public Domain”.

Hope, that won't get you in trouble …

**Comment by xem** [comment]
No worries, I didn't copy paste any code from the book, I read it (it's a tutorial), and wrote my lib based on what I learned. Use my code freely and fearlessly.

**Comment by Ryuno-Ki** [comment]
@baturinsky Do you mind creating a PR to add your game to the README?

**Comment by baturinsky** [comment]
I haven't used the lib in the end:) I did make a game with physics that time https://github.com/baturinsky/fat-kids-on-trampoline but I used some minimal ad hoc system, as I only needed circles bouncing out of each other.

**Comment by xem** [comment]
ooh, that's fun!
