### ISSUE TITLE
Cross product != outer product?

### ISSUE THREAD

**Issue by Ryuno-Ki** [xem/mini2Dphysics#2]
Hey Maxime!

Looking at

https://github.com/xem/mini2Dphysics/blob/356e8e44b00c0338d4488745fd9be65128a96b40/index.html#L16

I'm surprised to find a number as return value type.
I expected another Vec2.

What kind of product are you computing there?
It doesn't seem to be a https://en.wikipedia.org/wiki/Cross_product

(I'm adding tests and type annotations in my project, but that would interfer with the code gulf approach you took here).

**Comment by Ryuno-Ki** [comment]
Could it be the determinant of the matrix?
https://en.wikipedia.org/wiki/Determinant

**Comment by xem** [comment]
Hi Andre, i have to admit I 'm not an expert in this field.
My 2d physics libs is not invented by me, but a golfing of the code present in this book https://www.apress.com/gp/book/9781484225820 

Besides that, it seems that cross product is actually not defined for 2d vectors, so it' s not exactly true to call it that, but I don't know what else to call it. More info here https://stackoverflow.com/questions/243945/calculating-a-2d-vectors-cross-product

**Comment by Ryuno-Ki** [comment]
Oh.

It's really about time that I pull out my five years worth of math study and put it on the web, it seems.

From the quoted SO question:

> From a pure mathematical point of view the cross product in 2D space does not exist, the scalar version is the hack and a 2D cross product that returns a 2D vector makes no sense at all.

**Comment by Ryuno-Ki** [comment]
The question has been answered. I'm going to close this issue now.

Would you appreciate, if I explain a bit more about the vector math you implemented (while I'm adapting it to my entry)?
I'll drop the link in here then.

**Comment by xem** [comment]
absolutely! also, if you understand what the resolveCollisions function does, it's still a mystery to me. (The book I read gave the equations but didn't explain them) https://github.com/xem/mini2Dphysics/blob/gh-pages/index.html#L339-L414

**Comment by Ryuno-Ki** [comment]
I will need to understand in order to document them :D

Watch this space!
(see what I did there :D)

**Comment by xem** [comment]
awesome. Note that I golfed the circles collisions for js1k 2019
https://xem.github.io/codegolf/mini2Dphysics.html

you can see the comments I wrote for the restitution code here: https://github.com/xem/js1k19/blob/gh-pages/emojysics/index.html#L158-L198

**Comment by Ryuno-Ki** [comment]
Ain't no circles in my world yet.
I'm going with rectangles for now, since I can treat them as bounding boxes for my sprites in the future.

**Comment by Ryuno-Ki** [comment]
You could destructure assign the `Math` object for the trigonometric functions to squeeze a bit more bytes, perhaps.
