### ISSUE TITLE
Refactoring to take smaller parts?

### ISSUE THREAD

**Issue by Ryuno-Ki** [xem/mini2Dphysics#4]
Hey @xem,

while I was implementing the physics in my game, I was wondering, whether the code could be broken apart to be able to only take the parts required.

For example, if I don't need rotation, what code is not needed?

That would mean, breaking shapes into smaller objects (position, rotation, drawing info) and somehow keep a reference for each.
I'd guess, via the `objects` Array and its indices, that you already have.

Just a thought I want to throw into the room.

**Comment by xem** [comment]
Hi!

I'd say the project is so little that splitting it in modules wouldn't make a lot of sense.

But if you do a fork of this repo where you do it, I'll be happy to mention it in this repo's readme!

I suggest to remove all the code that is about rotation instead (for the example you mentioned).
The code comments should help doing this quite easily.

Cheers,
Max

**Comment by Ryuno-Ki** [comment]
Already doing that: https://jaenis.ch/hobbies/coding/repos/ryuno-ki/js13kgames-2021/src/branch/combat-scorched-earth-from-outer-space/src/js

The code is annotated with JSDoc (so I generate typings) and broken up into smaller chunks.

Yes, that will result in larger bundle sizes. But I prefer that over cryptic code if I have the option.

Could you add a README so people could PR „mini2Dphysics in the wild” with links to their project?

**Comment by Ryuno-Ki** [comment]
For the purpose of the competition, I keep a mirror on GitHub: https://github.com/Ryuno-Ki/js13kgames-2021/tree/combat-scorched-earth-from-outer-space/src/js - I won't accept any comments or issues there.

I plan to add WebMentions support to Gitea at some point, so tweets will be picked up.

**Comment by xem** [comment]
Readme added!
